# Generated by Django 5.2.13 on 2026-04-28 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('in_progress', 'В работе'), ('done', 'Завершен'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменен')], default='created', max_length=16),
        ),
        migrations.CreateModel(
            name='ExecutorServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offers', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_offers', to='marketplace.servicetype')),
            ],
            options={
                'verbose_name': 'Предложение исполнителя',
                'verbose_name_plural': 'Предложения исполнителей',
                'ordering': ('service_type__name', 'executor__username'),
                'unique_together': {('executor', 'service_type')},
            },
        ),
    ]
