# Generated by Django 5.2.13 on 2026-04-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cemetery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('burials_signed', models.IntegerField(blank=True, null=True, verbose_name='Подписанных захоронений')),
                ('burials_unsigned', models.IntegerField(blank=True, null=True, verbose_name='Неподписанных захоронений')),
                ('burials_total', models.IntegerField(blank=True, null=True, verbose_name='Всего захоронений')),
                ('people_signed', models.IntegerField(blank=True, null=True, verbose_name='Подписанных людей')),
                ('people_unsigned', models.IntegerField(blank=True, null=True, verbose_name='Неподписанных людей')),
                ('people_total', models.IntegerField(blank=True, null=True, verbose_name='Всего людей')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Кладбище',
                'verbose_name_plural': 'Кладбища',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='cem_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Burial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grave_number', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Номер участка')),
                ('has_tombstone', models.BooleanField(blank=True, null=True, verbose_name='Памятник установлен')),
                ('inscription', models.TextField(blank=True, verbose_name='Надпись на памятнике')),
                ('global_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Глобальный ID (mos.ru)')),
                ('geo_data', models.JSONField(blank=True, help_text='GeoJSON-структура: тип геометрии и координаты (Point/Polygon/MultiPolygon).', null=True, verbose_name='Геометрия захоронения')),
                ('geo_data_center', models.JSONField(blank=True, help_text='GeoJSON Point с центром для отображения маркера на карте.', null=True, verbose_name='Центральная точка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('cemetery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='burials', to='cemeteries.cemetery', verbose_name='Кладбище')),
            ],
            options={
                'verbose_name': 'Захоронение',
                'verbose_name_plural': 'Захоронения',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BurialPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.TextField(verbose_name='ФИО / подпись')),
                ('birth_date', models.CharField(blank=True, help_text='Сырая строка ДД.ММ.ГГГГ или год — данные из источника не унифицированы.', max_length=32, verbose_name='Дата рождения')),
                ('death_date', models.CharField(blank=True, max_length=32, verbose_name='Дата смерти')),
                ('birth_year', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Год рождения')),
                ('death_year', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Год смерти')),
                ('burial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='cemeteries.burial', verbose_name='Захоронение')),
            ],
            options={
                'verbose_name': 'Человек в захоронении',
                'verbose_name_plural': 'Люди в захоронениях',
                'ordering': ('burial_id', 'id'),
                'indexes': [models.Index(fields=['burial'], name='bp_burial_idx'), models.Index(fields=['birth_year'], name='bp_birth_year_idx'), models.Index(fields=['death_year'], name='bp_death_year_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='burial',
            index=models.Index(fields=['grave_number'], name='bur_grave_idx'),
        ),
        migrations.AddIndex(
            model_name='burial',
            index=models.Index(fields=['cemetery'], name='bur_cem_idx'),
        ),
    ]
